name: Deploy App1

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy files to server
        uses: burnett01/rsync-deployments@7.0.1
        with:
          switches: -avz --delete --exclude '.git' --exclude '.github'
          path: ./
          remote_path: /opt/apps/app1/
          remote_host: ${{ secrets.SERVER_IP }}
          remote_user: ${{ secrets.SERVER_USER }}
          remote_key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Build & Restart Container
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /opt/apps
            docker compose build php-app1
            docker compose up -d php-app1
            docker compose restart nginx